### ISSUE TITLE
 Initial Review

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-cronie#1]
Type of Report

Review Request
Actual behaviour

Role had no initial review.
Expected behaviour

**Comment by Cinux90** [comment]
- folder files and vars are empty -> can be deleted from my side
  maybe also template folder

- vars folder is empty but in Readme.md under Role Variables are information about the vars/secure.yml
  Maybe should be reviewed from your side

**Comment by daniel-schier** [comment]
thanks a lot :) fixes are addressed in #2
